name: chatos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #firebase related
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  #--------------------------
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.4
  skeletonizer: ^1.4.2
  multiavatar: ^0.1.5
  flutter_svg: ^2.0.10+1
  drop_down_search_field: ^1.0.5
  intl: ^0.19.0
  chat_bubbles: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:

  uses-material-design: true


  assets:
    - assets/webp/

# to generate app icon run 'dart run flutter_launcher_icons:generate'
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon/app_icon.webp"

