import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:multiavatar/multiavatar.dart';
class MultiAvatarGenerator extends StatelessWidget {
  const MultiAvatarGenerator({super.key, required this.code, this.side=40});
final String code;
final double side;

  @override
  Widget build(BuildContext context) {
    return Tooltip(
      message: 'Generated by Multiavatar',
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          SvgPicture.string(
            multiavatar(code, trBackground: false) ,
            height: side,
            width: side,
          ),
        ],
      ),
    );
  }
}
